---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Infrastructure prerequisites for Chef installation

Metadata: {}

Parameters:
  ChefName:
    Description: Supply name for whole Chef infrastructure
    Type: String
  ChefSecretsBucket:
    Description: Supply S3 Bucket name for the Chef Servers to read/write config files to
    Type: String
  ContactEmail:
    Description: Contact email for Cloudwatch notifications and instance tagging
    Type: String
  ContactDept:
    Description: Contact department for billing purposes
    Type: String

Mappings: {}

Conditions:
  ChefSecretsBucketNamed:
    !Not [!Equals [!Ref ChefSecretsBucket, '']]

Resources:
  ChefBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !If [ChefSecretsBucketNamed, !Ref ChefSecretsBucket, !Ref ChefName]
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      Tags:
      - Key: !Ref ChefName
        Value: !Sub ${AWS::StackName}-bootstrap-frontend
      - Key: X-Dept
        Value: !Ref ContactDept
      - Key: X-Contact
        Value: !Ref ContactEmail

Outputs: {}
