---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  IAM prerequisites for Chef installation

Metadata: {}

Parameters:
  ChefName:
    Description: Supply name for whole Chef infrastructure
    Type: String
  ChefSecretsBucket:
    Description: Supply an S3 Bucket name for the Chef Servers to read/write config files to
    Type: String

Mappings: {}

Conditions:
  ChefSecretsBucketNamed:
    !Not [!Equals [!Ref ChefSecretsBucket, '']]

Resources:

  #
  # Chef Server IAM setup
  #

  ChefRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ChefName}-server-role
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action:
          - sts:AssumeRole
          Principal:
            Service:
            - ec2.amazonaws.com
          Effect: Allow
      ManagedPolicyArns:
        - !Join [ ':', ['arn:aws:iam:', !Ref 'AWS::AccountId', 'policy/cs/awsiam-sauce'] ]
        - !Join [ ':', ['arn:aws:iam:', !Ref 'AWS::AccountId', 'policy/cs/awsiam-sauce-the-sequel'] ]

  ChefRolePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: chef-policy
      Roles:
      - !Ref ChefRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        # Allow all actions to one bucket (the supplied one, or the one you provided)
        - Action: s3:*
          Effect: Allow
          Resource:
            - !Join [ '', ['arn:aws:s3:::', !If [ChefSecretsBucketNamed, !Ref ChefSecretsBucket, !Ref ChefName]] ]
            - !Join [ '', ['arn:aws:s3:::', !If [ChefSecretsBucketNamed, !Ref ChefSecretsBucket, !Ref ChefName], '/*'] ]
        # Allow ability to list all buckets
        - Action: s3:List*
          Effect: Allow
          Resource: arn:aws:s3:::*
        # Allow instances to set themselves as unhealthy if one of the scripts fail
        - Action: autoscaling:*
          Effect: Allow
          Resource: "*"
        # Allow instances to read their own tags (needed for setup script below)
        - Action: ec2:DescribeTags
          Effect: Allow
          Resource: "*"
        - Action: cloudwatch:PutMetricData
          Effect: Allow
          Resource: "*"
        - Action: cloudwatch:GetMetricStatistics
          Effect: Allow
          Resource: "*"
        - Action: cloudwatch:ListMetrics
          Effect: Allow
          Resource: "*"
        # Allow instances to write to cloudwatch logs
        - Action: ["logs:PutLogEvents", "logs:CreateLogStream", "logs:CreateLogGroup"]
          Effect: Allow
          # Server instances have to be created in stack called ${ChefName}-server
          Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${ChefName}-server-*

  ChefInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub ${ChefName}-server-profile
      Path: /
      Roles:
      - !Ref ChefRole

  #
  # Automare Server IAM setup
  #

  AutomateRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ChefName}-automate-role
      Path: /
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
        - !Join [ ':', ['arn:aws:iam:', !Ref 'AWS::AccountId', 'policy/cs/awsiam-sauce'] ]
        - !Join [ ':', ['arn:aws:iam:', !Ref 'AWS::AccountId', 'policy/cs/awsiam-sauce-the-sequel'] ]

  AutomateRolePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: automate-policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        # Allow instance to create a nightly snapshot
        - Action: ["ec2:CreateSnapshot", "ec2:CreateTags", "ec2:DeleteSnapshot", "ec2:DescribeSnapshots", "ec2:DescribeVolumes"]
          Effect: Allow
          Resource: "*"
        # Allow instances to read their own tags (needed for setup script below)
        - Action: ec2:DescribeTags
          Effect: Allow
          Resource: "*"
        - Action: cloudwatch:PutMetricData
          Effect: Allow
          Resource: "*"
        - Action: cloudwatch:GetMetricStatistics
          Effect: Allow
          Resource: "*"
        - Action: cloudwatch:ListMetrics
          Effect: Allow
          Resource: "*"
        # Allow instances to write to cloudwatch logs
        - Action: ["logs:PutLogEvents", "logs:CreateLogStream", "logs:CreateLogGroup"]
          Effect: Allow
          # Automate instance has to be created in stack called ${ChefName}-automate
          Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${ChefName}-automate-*
      Roles:
      - !Ref AutomateRole

  AutomateInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub ${ChefName}-automate-profile
      Path: /
      Roles:
      - !Ref AutomateRole

Outputs: {}
