#
# Chef Server IAM setup
#

---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  IAM prerequisites for Chef installation

Metadata: {}

Parameters:
  ChefName:
    Description: Supply name for whole Chef infrastructure
    Type: String
  ChefSecretsBucket:
    Description: Supply an S3 Bucket name for the Chef Servers to read/write config files to
    Type: String

Mappings: {}

Conditions: {}

Resources:

  ChefRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ChefName}-role
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action:
          - sts:AssumeRole
          Principal:
            Service:
            - ec2.amazonaws.com
          Effect: Allow
      ManagedPolicyArns:
        - !Join [ ':', ['arn:aws:iam:', !Ref 'AWS::AccountId', 'policy/cs/awsiam-sauce'] ]
        - !Join [ ':', ['arn:aws:iam:', !Ref 'AWS::AccountId', 'policy/cs/awsiam-sauce-the-sequel'] ]

  RolePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: chef-policy
      Roles:
      - !Ref ChefRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        # Allow all actions to one bucket (the supplied one, or the one you provided)
        - Action: s3:*
          Effect: Allow
          Resource:
            - !Join ['', [ 'arn:aws:s3:::', !Ref ChefSecretsBucket ]]
            - !Join ['', [ 'arn:aws:s3:::', !Ref ChefSecretsBucket, '/*' ]]
        # Allow ability to list all buckets
        - Action: s3:List*
          Effect: Allow
          Resource: arn:aws:s3:::*
        # Allow instances to set themselves as unhealthy if one of the scripts fail
        - Action: autoscaling:*
          Effect: Allow
          Resource: "*"
        # Allow instance to create a nightly snapshot
        - Action: ["ec2:CreateSnapshot", "ec2:CreateTags", "ec2:DeleteSnapshot", "ec2:DescribeSnapshots", "ec2:DescribeVolumes"]
          Effect: Allow
          Resource: "*"
        # Allow instances to read their own tags (needed for setup script below)
        - Action: ec2:DescribeTags
          Effect: Allow
          Resource: "*"
        - Action: cloudwatch:PutMetricData
          Effect: Allow
          Resource: "*"
        - Action: cloudwatch:GetMetricStatistics
          Effect: Allow
          Resource: "*"
        - Action: cloudwatch:ListMetrics
          Effect: Allow
          Resource: "*"
        # Allow instances to write to cloudwatch logs
        - Action: ["logs:PutLogEvents", "logs:CreateLogStream", "logs:CreateLogGroup"]
          Effect: Allow
          Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*

Outputs: {}
